package com.yigit.buds2blescanner;

import android.Manifest;
import android.annotation.SuppressLint;
import android.app.*;
import android.bluetooth.*;
import android.bluetooth.le.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.os.*;
import android.os.ParcelUuid;
import android.util.SparseArray;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;

public class MainActivity extends Activity {
    private static final int REQ=1001, CREATE_FILE=2001;
    private static final long SCAN_MS=15000, RETRY_MS=1200;
    private static final UUID SPP=UUID.fromString("00001101-0000-1000-8000-00805F9B34FB");
    private BluetoothAdapter adapter; private BluetoothLeScanner scanner; private BluetoothGatt gatt;
    private BluetoothSocket rfcomm; private InputStream rfIn; private OutputStream rfOut;
    private final Handler handler=new Handler(Looper.getMainLooper());
    private TextView status,selectedInfo,count,log; private LinearLayout deviceList,pairedList;
    private Button scan,bleConnect,classicConnect,disconnect,save,clear;
    private final LinkedHashMap<String,DeviceRow> devices=new LinkedHashMap<>();
    private BluetoothDevice selected; private String selectedName="unknown",selectedBleAddress="unknown",selectedClassicAddress="unknown";
    private boolean scanning,manualDisconnect,connecting; private int attempts; private String pendingExport="";
    private final Set<String> notifySet=new HashSet<>(); private final ArrayList<BluetoothGattCharacteristic> readQueue=new ArrayList<>(); private int readIndex;
    private final StringBuilder capture=new StringBuilder(); private boolean firstEvent=true; private final AtomicBoolean classicReading=new AtomicBoolean(false);
    private final BudsProtocolAnalyzer protocolAnalyzer=new BudsProtocolAnalyzer();
    static class DeviceRow { BluetoothDevice d; TextView title,sub,extra; int rssi,tx; boolean connectable; ScanRecord record; DeviceRow(BluetoothDevice d){this.d=d;} }

    @Override public void onCreate(Bundle b){super.onCreate(b);BluetoothManager bm=(BluetoothManager)getSystemService(Context.BLUETOOTH_SERVICE);adapter=bm.getAdapter();buildUi();requestBtPermissions();}
    private void buildUi(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(10),dp(6),dp(10),dp(6));
        root.addView(label("Galaxy Buds2 Professional Analyzer",22));status=label("● Hazır",14);root.addView(status);
        LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);scan=button("BLE TARA");bleConnect=button("BLE BAĞLAN");classicConnect=button("CLASSIC / RFCOMM");disconnect=button("KES");save=button("CAPTURE KAYDET");
        bleConnect.setEnabled(false);classicConnect.setEnabled(false);disconnect.setEnabled(false);save.setEnabled(false);
        scan.setOnClickListener(v->toggleScan());bleConnect.setOnClickListener(v->{if(selected!=null)connectBle(selected);});classicConnect.setOnClickListener(v->{if(selected!=null)connectClassic(selected);});disconnect.setOnClickListener(v->disconnectAll());save.setOnClickListener(v->saveCapture());bar.addView(scan,w());bar.addView(bleConnect,w());bar.addView(classicConnect,w());bar.addView(disconnect,w());bar.addView(save,w());root.addView(bar);
        selectedInfo=label("Cihaz seçilmedi — BLE listesinden veya eşleşmiş cihazlardan seç",12);root.addView(selectedInfo);count=label("0 BLE cihaz",11);root.addView(count);
        ScrollView ds=new ScrollView(this);deviceList=new LinearLayout(this);deviceList.setOrientation(LinearLayout.VERTICAL);ds.addView(deviceList);root.addView(ds,new LinearLayout.LayoutParams(-1,dp(250)));
        root.addView(label("EŞLEŞMİŞ / CLASSIC DEVİCE'LAR",13));ScrollView ps=new ScrollView(this);pairedList=new LinearLayout(this);pairedList.setOrientation(LinearLayout.VERTICAL);ps.addView(pairedList);root.addView(ps,new LinearLayout.LayoutParams(-1,dp(130)));
        LinearLayout lh=new LinearLayout(this);lh.addView(label("LIVE PROTOCOL / GATT / RFCOMM / HEX",12),new LinearLayout.LayoutParams(0,-2,1));clear=button("TEMİZLE");clear.setOnClickListener(v->log.setText(""));lh.addView(clear);root.addView(lh);
        ScrollView ls=new ScrollView(this);log=label("",10);log.setTextIsSelectable(true);ls.addView(log);root.addView(ls,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);refreshBonded();}
    private TextView label(String s,float z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setPadding(0,dp(2),0,dp(2));return t;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}private LinearLayout.LayoutParams w(){return new LinearLayout.LayoutParams(0,-2,1);}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
    private void requestBtPermissions(){if(Build.VERSION.SDK_INT>=31){if(checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)!=PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.BLUETOOTH_SCAN,Manifest.permission.BLUETOOTH_CONNECT},REQ);}else if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION},REQ);}
    @SuppressLint("MissingPermission")private boolean ready(){if(adapter==null){msg("Bluetooth desteklenmiyor");return false;}if(!adapter.isEnabled()){msg("Bluetooth kapalı");return false;}return Build.VERSION.SDK_INT<31||(checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)==PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)==PackageManager.PERMISSION_GRANTED);}
    private void newCapture(){capture.setLength(0);firstEvent=true;notifySet.clear();readQueue.clear();readIndex=0;protocolAnalyzer.reset();event("CAPTURE_START","app=Galaxy Buds2 Professional Analyzer;version=4");}
    private void event(String type,String data){synchronized(capture){if(!firstEvent)capture.append(",\n");firstEvent=false;capture.append("{\"time\":\"").append(esc(ts())).append("\",\"type\":\"").append(esc(type)).append("\",\"data\":\"").append(esc(data)).append("\"}");}}
    private String esc(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n");}private String ts(){return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ",Locale.US).format(new Date());}
    @SuppressLint("MissingPermission")private void toggleScan(){if(scanning){stopScan();return;}if(!ready())return;devices.clear();deviceList.removeAllViews();scanner=adapter.getBluetoothLeScanner();if(scanner==null){msg("BLE scanner alınamadı");return;}newCapture();scanning=true;scan.setText("DURDUR");status.setText("● BLE scan aktif");event("BLE_SCAN_START","low_latency");scanner.startScan(null,new ScanSettings.Builder().setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY).setReportDelay(0).build(),scanCallback);handler.postDelayed(this::stopScan,SCAN_MS);}
    @SuppressLint("MissingPermission")private void stopScan(){if(!scanning)return;scanning=false;if(scanner!=null)scanner.stopScan(scanCallback);scan.setText("BLE TARA");if(gatt==null)status.setText("● BLE taraması tamamlandı");event("BLE_SCAN_END","devices="+devices.size());}
    private final ScanCallback scanCallback=new ScanCallback(){@Override public void onScanResult(int type,ScanResult r){BluetoothDevice d=r.getDevice();String a=safeAddress(d);DeviceRow row=devices.get(a);if(row==null){row=new DeviceRow(d);devices.put(a,row);addCard(row);}row.rssi=r.getRssi();row.tx=r.getTxPower();row.record=r.getScanRecord();row.connectable=Build.VERSION.SDK_INT<26||r.isConnectable();updateCard(row);event("BLE_ADVERTISEMENT","name="+safeName(d)+";bleAddress="+a+";rssi="+r.getRssi()+";tx="+r.getTxPower()+";connectable="+row.connectable+";services="+(row.record==null?"":row.record.getServiceUuids())+";manufacturer="+manufacturer(row.record)+";serviceData="+serviceData(row.record)+";raw="+hex(row.record==null?null:row.record.getBytes()));} @Override public void onScanFailed(int e){event("BLE_SCAN_ERROR","code="+e);runOnUiThread(()->{status.setText("● BLE scan error "+e);scan.setText("BLE TARA");scanning=false;});}};
    @SuppressLint("MissingPermission")private void addCard(DeviceRow r){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(8),dp(5),dp(8),dp(5));c.setBackgroundResource(android.R.drawable.dialog_holo_light_frame);r.title=label("",15);r.sub=label("",11);r.extra=label("",10);c.addView(r.title);c.addView(r.sub);c.addView(r.extra);c.setOnClickListener(v->select(r));c.setOnLongClickListener(v->{details(r);return true;});deviceList.addView(c,new LinearLayout.LayoutParams(-1,dp(90)));updateCard(r);}
    @SuppressLint("MissingPermission")private void updateCard(DeviceRow r){if(r.title==null)return;r.title.setText((selected==r.d?"✓ ":"")+safeName(r.d));r.sub.setText(safeAddress(r.d)+" | RSSI "+r.rssi+" dBm | "+(r.connectable?"CONNECTABLE":"NON-CONNECTABLE"));r.extra.setText("TX "+r.tx+" | Bond "+bond(r.d)+" | Dokun: seç • uzun bas: inspector");count.setText(devices.size()+" BLE cihaz");}
    @SuppressLint("MissingPermission")private void select(DeviceRow r){selected=r.d;selectedName=safeName(r.d);selectedBleAddress=safeAddress(r.d);bleConnect.setEnabled(gatt==null);classicConnect.setEnabled(true);selectedInfo.setText("SEÇİLİ: "+selectedName+"\nBLE address: "+selectedBleAddress+" | Bond: "+bond(r.d)+" | AddressType: "+addressType(r.d));for(DeviceRow x:devices.values())updateCard(x);event("DEVICE_SELECTED",identity(r));status.setText("● Cihaz seçildi — bağlantı yöntemini seç");}
    @SuppressLint("MissingPermission")private void details(DeviceRow r){StringBuilder s=new StringBuilder();s.append("Name: ").append(safeName(r.d)).append("\nBLE address: ").append(safeAddress(r.d)).append("\nAddress type: ").append(addressType(r.d)).append("\nBond: ").append(bond(r.d)).append("\nRSSI: ").append(r.rssi).append("\nConnectable: ").append(r.connectable).append("\nTX: ").append(r.tx).append("\n");if(r.record!=null)s.append("Services: ").append(r.record.getServiceUuids()).append("\nManufacturer: ").append(manufacturer(r.record)).append("\nServiceData: ").append(serviceData(r.record)).append("\nRAW:\n").append(hex(r.record.getBytes()));new AlertDialog.Builder(this).setTitle("Bluetooth Device Inspector").setMessage(s.toString()).setPositiveButton("SEÇ",(d,w)->select(r)).setNeutralButton("KAPAT",null).show();}
    private String identity(DeviceRow r){return "name="+safeName(r.d)+";bleAddress="+safeAddress(r.d)+";addressType="+addressType(r.d)+";bond="+bond(r.d)+";rssi="+r.rssi+";connectable="+r.connectable;}
    @SuppressLint("MissingPermission")private void connectBle(BluetoothDevice d){stopScan();disconnectGatt();manualDisconnect=false;connecting=true;attempts=0;newCapture();event("BLE_CONNECT_START",identity(find(d)));bleConnect.setEnabled(false);classicConnect.setEnabled(false);disconnect.setEnabled(true);save.setEnabled(true);startBleAttempt();}
    private DeviceRow find(BluetoothDevice d){for(DeviceRow r:devices.values())if(r.d.equals(d))return r;return new DeviceRow(d);}
    @SuppressLint("MissingPermission")private void startBleAttempt(){if(selected==null)return;int n=++attempts;event("BLE_CONNECT_ATTEMPT","attempt="+n+";transport=AUTO;bleAddress="+selectedBleAddress);append("BLE CONNECT "+n+"/3 → TRANSPORT_AUTO");status.setText("● BLE bağlanıyor "+n+"/3");gatt=selected.connectGatt(this,false,gattCallback,BluetoothDevice.TRANSPORT_AUTO);}
    private void bleRetry(int code){if(manualDisconnect)return;if(attempts<3){event("BLE_CONNECT_RETRY","after="+code+";next="+(attempts+1));disconnectGatt();handler.postDelayed(this::startBleAttempt,RETRY_MS*attempts);}else{connecting=false;event("BLE_CONNECT_FAILED","status="+code+";name="+gattStatus(code));runOnUiThread(()->{status.setText("● BLE başarısız: "+code+" / "+gattStatus(code));bleConnect.setEnabled(selected!=null);classicConnect.setEnabled(true);disconnect.setEnabled(false);});}}
    @SuppressLint("MissingPermission")private void disconnectGatt(){if(gatt!=null){try{gatt.disconnect();}catch(Exception ignored){}try{gatt.close();}catch(Exception ignored){}gatt=null;}}
    private final BluetoothGattCallback gattCallback=new BluetoothGattCallback(){@Override public void onConnectionStateChange(BluetoothGatt g,int st,int state){event("GATT_STATE","state="+state+";status="+st+";name="+gattStatus(st));if(state==BluetoothGatt.STATE_CONNECTED){connecting=false;event("BLE_CONNECTED","status="+st);status.setText("● BLE BAĞLI → MTU / GATT discovery");if(Build.VERSION.SDK_INT>=21)g.requestMtu(517);else g.discoverServices();}else if(state==BluetoothGatt.STATE_DISCONNECTED)bleRetry(st);}
      @Override public void onMtuChanged(BluetoothGatt g,int mtu,int st){event("MTU","mtu="+mtu+";status="+st);g.discoverServices();}
      @Override public void onServicesDiscovered(BluetoothGatt g,int st){if(st!=BluetoothGatt.GATT_SUCCESS){event("GATT_DISCOVERY_ERROR","status="+st);return;}append("=== GATT "+g.getServices().size()+" SERVICES ===");event("GATT_DISCOVERY","services="+g.getServices().size());for(BluetoothGattService s:g.getServices()){append("SERVICE "+s.getUuid());event("SERVICE",s.getUuid().toString());for(BluetoothGattCharacteristic c:s.getCharacteristics()){String p=props(c.getProperties());append(" CHAR "+c.getUuid()+" ["+p+"]");event("CHARACTERISTIC",c.getUuid()+";properties="+p);for(BluetoothGattDescriptor d:c.getDescriptors()){event("DESCRIPTOR",d.getUuid().toString());append("  DESC "+d.getUuid());}if((c.getProperties()&BluetoothGattCharacteristic.PROPERTY_READ)!=0)readQueue.add(c);if((c.getProperties()&(BluetoothGattCharacteristic.PROPERTY_NOTIFY|BluetoothGattCharacteristic.PROPERTY_INDICATE))!=0)enableNotify(c);}}readNext();}
      @Override public void onCharacteristicRead(BluetoothGatt g,BluetoothGattCharacteristic c,byte[] v,int st){event("READ","uuid="+c.getUuid()+";status="+st+";hex="+hex(v));append("READ "+c.getUuid()+" → "+hex(v));readIndex++;handler.postDelayed(MainActivity.this::readNext,100);}
      @Override public void onCharacteristicChanged(BluetoothGatt g,BluetoothGattCharacteristic c,byte[] v){event("NOTIFY","uuid="+c.getUuid()+";hex="+hex(v));append("NOTIFY "+c.getUuid()+" → "+hex(v));}
      @Override public void onDescriptorWrite(BluetoothGatt g,BluetoothGattDescriptor d,int st){event("DESCRIPTOR_WRITE","uuid="+d.getUuid()+";status="+st);}
    };
    @SuppressLint("MissingPermission")private void readNext(){if(gatt!=null&&readIndex<readQueue.size()){gatt.readCharacteristic(readQueue.get(readIndex));}else{event("GATT_CAPTURE_READY","reads="+readQueue.size()+";notifications="+notifySet.size());status.setText("● GATT capture hazır");}}
    @SuppressLint("MissingPermission")private void enableNotify(BluetoothGattCharacteristic c){String u=c.getUuid().toString();if(gatt==null||notifySet.contains(u))return;notifySet.add(u);boolean ok=gatt.setCharacteristicNotification(c,true);event("NOTIFY_ENABLE",u+";local="+ok);BluetoothGattDescriptor d=c.getDescriptor(UUID.fromString("00002902-0000-1000-8000-00805F9B34FB"));if(d!=null){d.setValue((c.getProperties()&BluetoothGattCharacteristic.PROPERTY_INDICATE)!=0?BluetoothGattDescriptor.ENABLE_INDICATION_VALUE:BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE);gatt.writeDescriptor(d);}}
    @SuppressLint("MissingPermission")private void refreshBonded(){pairedList.removeAllViews();if(!ready())return;for(BluetoothDevice d:adapter.getBondedDevices()){Button b=button("● "+safeName(d)+"\nClassic/BR-EDR: "+safeAddress(d)+" | Bonded\nDokun: seç • SDP/UUID: sorgula");b.setAllCaps(false);b.setOnClickListener(v->{selected=d;selectedName=safeName(d);selectedClassicAddress=safeAddress(d);classicConnect.setEnabled(true);bleConnect.setEnabled(true);selectedInfo.setText("SEÇİLİ CLASSIC: "+selectedName+"\nClassic address: "+selectedClassicAddress+" | Bond: "+bond(d));event("CLASSIC_DEVICE_SELECTED","name="+selectedName+";classicAddress="+selectedClassicAddress+";bond="+bond(d));fetchSdp(d);});pairedList.addView(b);}}
    @SuppressLint("MissingPermission")private void fetchSdp(BluetoothDevice d){event("SDP_QUERY_START","address="+safeAddress(d));append("SDP/UUID query → "+safeAddress(d));try{d.fetchUuidsWithSdp();}catch(Exception e){append("SDP ERROR "+e);event("SDP_ERROR",String.valueOf(e));}handler.postDelayed(()->showUuids(d),1800);}
    @SuppressLint("MissingPermission")private void showUuids(BluetoothDevice d){ParcelUuid[] u=d.getUuids();if(u==null||u.length==0){append("No SDP UUIDs returned");event("SDP_RESULT","none");return;}StringBuilder s=new StringBuilder();for(ParcelUuid x:u)s.append(x.getUuid()).append("\n");append("SDP UUIDs:\n"+s);event("SDP_RESULT",s.toString());}
    @SuppressLint("MissingPermission")private void connectClassic(BluetoothDevice d){if(!ready())return;if(d.getBondState()!=BluetoothDevice.BOND_BONDED){msg("Classic/RFCOMM için önce Android Bluetooth ayarlarından Buds2'yi eşleştir");return;}disconnectClassic();manualDisconnect=false;newCapture();selectedClassicAddress=safeAddress(d);event("RFCOMM_CONNECT_START","name="+safeName(d)+";classicAddress="+selectedClassicAddress);status.setText("● CLASSIC/RFCOMM bağlanıyor…");disconnect.setEnabled(true);save.setEnabled(true);new Thread(()->{BluetoothSocket s=null;try{ParcelUuid[] uuids=d.getUuids();List<UUID> candidates=new ArrayList<>();if(uuids!=null)for(ParcelUuid p:uuids)candidates.add(p.getUuid());if(!candidates.contains(SPP))candidates.add(SPP);for(UUID u:candidates){if(manualDisconnect)break;append("RFCOMM try UUID "+u);event("RFCOMM_ATTEMPT","uuid="+u);try{s=d.createRfcommSocketToServiceRecord(u);s.connect();rfcomm=s;rfIn=s.getInputStream();rfOut=s.getOutputStream();event("RFCOMM_CONNECTED","uuid="+u+";remote="+selectedClassicAddress);runOnUiThread(()->status.setText("● RFCOMM BAĞLI — pasif capture aktif"));startClassicReader();return;}catch(Exception ex){event("RFCOMM_FAIL","uuid="+u+";error="+ex);try{if(s!=null)s.close();}catch(Exception ignored){}s=null;}}append("RFCOMM: no usable SDP channel");runOnUiThread(()->status.setText("● RFCOMM bağlantısı kurulamadı"));}catch(Exception e){event("RFCOMM_ERROR",String.valueOf(e));runOnUiThread(()->status.setText("● RFCOMM hata: "+e.getClass().getSimpleName()));}}).start();}
    private void startClassicReader(){if(rfIn==null)return;classicReading.set(true);new Thread(()->{byte[] buf=new byte[4096];try{while(classicReading.get()&&rfIn!=null){int n=rfIn.read(buf);if(n>0){byte[] v=Arrays.copyOf(buf,n);String h=hex(v);event("RFCOMM_RX",h);append("RFCOMM RX "+n+" bytes → "+h);for(BudsProtocolAnalyzer.Frame f:protocolAnalyzer.feed(v)){String summary=f.summary();event("RFCOMM_FRAME_ANALYSIS",summary);append("ANALYZER #"+protocolAnalyzer.frameCount()+" → "+summary);}}}}catch(Exception e){if(classicReading.get()){event("RFCOMM_READ_ERROR",String.valueOf(e));append("RFCOMM read stopped: "+e);}}}).start();}
    private void disconnectClassic(){classicReading.set(false);try{if(rfIn!=null)rfIn.close();}catch(Exception ignored){}try{if(rfOut!=null)rfOut.close();}catch(Exception ignored){}try{if(rfcomm!=null)rfcomm.close();}catch(Exception ignored){}rfIn=null;rfOut=null;rfcomm=null;}
    private void disconnectAll(){manualDisconnect=true;handler.removeCallbacksAndMessages(null);disconnectClassic();disconnectGatt();connecting=false;event("DISCONNECT_ALL","manual");runOnUiThread(()->{disconnect.setEnabled(false);bleConnect.setEnabled(selected!=null);classicConnect.setEnabled(selected!=null);status.setText("● Bağlantılar kesildi");});}
    private void saveCapture(){String body="{\n\"format\":\"GalaxyBudsCapture\",\n\"version\":4,\n\"deviceName\":\""+esc(selectedName)+"\",\n\"bleAddress\":\""+esc(selectedBleAddress)+"\",\n\"classicAddress\":\""+esc(selectedClassicAddress)+"\",\n\"events\":[\n"+capture+"\n],\n\"finished\":\""+ts()+"\"\n}\n";Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"buds2_full_capture_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date())+".json");pendingExport=body;startActivityForResult(i,CREATE_FILE);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==CREATE_FILE&&c==RESULT_OK&&d!=null)try(OutputStream o=getContentResolver().openOutputStream(d.getData())){o.write(pendingExport.getBytes("UTF-8"));append("CAPTURE KAYDEDİLDİ: "+d.getData());status.setText("● Capture kaydedildi");}catch(Exception e){append("SAVE ERROR "+e);}}
    private String props(int p){StringBuilder s=new StringBuilder();if((p&BluetoothGattCharacteristic.PROPERTY_READ)!=0)s.append("READ ");if((p&BluetoothGattCharacteristic.PROPERTY_WRITE)!=0)s.append("WRITE ");if((p&BluetoothGattCharacteristic.PROPERTY_WRITE_NO_RESPONSE)!=0)s.append("WRITE_NR ");if((p&BluetoothGattCharacteristic.PROPERTY_NOTIFY)!=0)s.append("NOTIFY ");if((p&BluetoothGattCharacteristic.PROPERTY_INDICATE)!=0)s.append("INDICATE ");if((p&BluetoothGattCharacteristic.PROPERTY_BROADCAST)!=0)s.append("BROADCAST ");return s.toString().trim();}
    private String hex(byte[] a){if(a==null)return"null";StringBuilder s=new StringBuilder();for(byte b:a)s.append(String.format(Locale.US,"%02X ",b&255));return s.toString().trim();}
    @SuppressLint("MissingPermission")private String safeName(BluetoothDevice d){try{return d.getName()==null?"unknown":d.getName();}catch(Exception e){return"unknown";}}@SuppressLint("MissingPermission")private String safeAddress(BluetoothDevice d){try{return d.getAddress();}catch(Exception e){return"unknown";}}
    @SuppressLint("MissingPermission")private String bond(BluetoothDevice d){try{int b=d.getBondState();return b==BluetoothDevice.BOND_BONDED?"BONDED":b==BluetoothDevice.BOND_BONDING?"BONDING":"NONE";}catch(Exception e){return"UNKNOWN";}}
    private String addressType(BluetoothDevice d){return "Android-resolved/OS-managed";}
    private String manufacturer(ScanRecord r){if(r==null)return"";SparseArray<byte[]> m=r.getManufacturerSpecificData();StringBuilder s=new StringBuilder();for(int i=0;i<m.size();i++)s.append(Integer.toHexString(m.keyAt(i))).append(":").append(hex(m.valueAt(i))).append(";");return s.toString();}
    private String serviceData(ScanRecord r){if(r==null)return"";Map<ParcelUuid,byte[]> m=r.getServiceData();if(m==null)return"";StringBuilder s=new StringBuilder();for(Map.Entry<ParcelUuid,byte[]> e:m.entrySet())s.append(e.getKey()).append(":").append(hex(e.getValue())).append(";");return s.toString();}
    private String gattStatus(int x){switch(x){case 0:return"GATT_SUCCESS";case 8:return"GATT_CONN_TIMEOUT_LEGACY";case 19:return"GATT_CONN_TERMINATE_PEER_USER";case 22:return"GATT_CONN_TERMINATE_LOCAL_HOST";case 133:return"GATT_FAILURE";case 257:return"GATT_ERROR_257";case 147:return"GATT_CONNECTION_TIMEOUT";default:return"GATT_STATUS_"+x;}}
    private void append(String s){runOnUiThread(()->log.append(new SimpleDateFormat("HH:mm:ss.SSS",Locale.US).format(new Date())+"  "+s+"\n"));}private void msg(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_LONG).show());}
    @Override protected void onDestroy(){disconnectAll();super.onDestroy();}
}
