package com.yigit.buds2blescanner;

import android.Manifest;
import android.annotation.SuppressLint;
import android.app.*;
import android.bluetooth.*;
import android.bluetooth.le.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    private static final int REQ=1001, CREATE_FILE=2001;
    private static final long SCAN_MS=15000, RETRY_BASE_MS=1200;
    private BluetoothAdapter adapter; private BluetoothLeScanner scanner; private BluetoothGatt gatt;
    private final Handler handler=new Handler(Looper.getMainLooper());
    private LinearLayout deviceList; private TextView status,count,selectedInfo,log;
    private Button scan,connect,disconnect,save,clear;
    private BluetoothDevice selected; private String selectedName="unknown",selectedAddress="unknown";
    private final LinkedHashMap<String,DeviceRow> devices=new LinkedHashMap<>();
    private final Set<String> notifySet=new HashSet<>(); private final ArrayList<BluetoothGattCharacteristic> readQueue=new ArrayList<>();
    private int readIndex,retryCount; private boolean scanning,manualDisconnect,connecting; private String pendingExport="";
    private final StringBuilder capture=new StringBuilder(); private boolean firstEvent=true;
    private final Runnable retryRunnable=this::startGattAttempt;
    static class DeviceRow { BluetoothDevice device; TextView card; int rssi; ScanRecord record; boolean connectable; int txPower; DeviceRow(BluetoothDevice d){device=d;} }

    @Override public void onCreate(Bundle b){super.onCreate(b);BluetoothManager bm=(BluetoothManager)getSystemService(BLUETOOTH_SERVICE);adapter=bm.getAdapter();buildUi();requestBtPermissions();}
    private void buildUi(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(12),dp(8),dp(12),dp(8));
        root.addView(label("Galaxy Buds2 Analyzer",24));status=label("● Hazır",15);root.addView(status);
        LinearLayout a=new LinearLayout(this);a.setOrientation(LinearLayout.HORIZONTAL);scan=button("TARA");connect=button("BAĞLAN");disconnect=button("KES");save=button("CAPTURE");connect.setEnabled(false);disconnect.setEnabled(false);save.setEnabled(false);
        scan.setOnClickListener(v->toggleScan());connect.setOnClickListener(v->{if(selected!=null)connectDevice(selected);});disconnect.setOnClickListener(v->disconnect());save.setOnClickListener(v->saveCapture());a.addView(scan,weight());a.addView(connect,weight());a.addView(disconnect,weight());a.addView(save,weight());root.addView(a);
        LinearLayout sb=new LinearLayout(this);sb.setOrientation(LinearLayout.VERTICAL);selectedInfo=label("Cihaz seçilmedi — listeden bir cihaza dokun",13);count=label("0 cihaz",12);sb.addView(selectedInfo);sb.addView(count);root.addView(sb);
        ScrollView ds=new ScrollView(this);deviceList=new LinearLayout(this);deviceList.setOrientation(LinearLayout.VERTICAL);ds.addView(deviceList);root.addView(ds,new LinearLayout.LayoutParams(-1,dp(300)));
        LinearLayout lh=new LinearLayout(this);lh.setOrientation(LinearLayout.HORIZONTAL);lh.addView(label("CANLI ANALİZ / GATT / HEX",13),new LinearLayout.LayoutParams(0,-2,1));clear=button("TEMİZLE");clear.setOnClickListener(v->log.setText(""));lh.addView(clear);root.addView(lh);
        ScrollView ls=new ScrollView(this);log=label("",11);log.setTextIsSelectable(true);ls.addView(log);root.addView(ls,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
    }
    private TextView label(String s,float z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setPadding(0,dp(3),0,dp(3));return t;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}private LinearLayout.LayoutParams weight(){return new LinearLayout.LayoutParams(0,-2,1);}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
    private void requestBtPermissions(){if(Build.VERSION.SDK_INT>=31){if(checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)!=PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.BLUETOOTH_SCAN,Manifest.permission.BLUETOOTH_CONNECT},REQ);}else if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION},REQ);}
    @SuppressLint("MissingPermission")private boolean ready(){if(adapter==null){msg("Bluetooth desteklenmiyor");return false;}if(!adapter.isEnabled()){msg("Bluetooth kapalı — lütfen açın");return false;}return Build.VERSION.SDK_INT<31||(checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)==PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)==PackageManager.PERMISSION_GRANTED);}
    @SuppressLint("MissingPermission")private void toggleScan(){if(scanning){stopScan();return;}if(!ready())return;devices.clear();deviceList.removeAllViews();selected=null;connect.setEnabled(false);scanner=adapter.getBluetoothLeScanner();if(scanner==null){msg("BLE Scanner kullanılamıyor");return;}newCapture();scanning=true;scan.setText("DURDUR");status.setText("● BLE taraması aktif");event("SCAN_START","mode=LOW_LATENCY");scanner.startScan(null,new ScanSettings.Builder().setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY).setReportDelay(0).build(),scanCallback);handler.postDelayed(this::stopScan,SCAN_MS);}
    @SuppressLint("MissingPermission")private void stopScan(){if(!scanning)return;scanning=false;if(scanner!=null)scanner.stopScan(scanCallback);scan.setText("TARA");if(gatt==null)status.setText("● Tarama tamamlandı");event("SCAN_END","devices="+devices.size());}
    private final ScanCallback scanCallback=new ScanCallback(){@Override public void onScanResult(int type,ScanResult r){BluetoothDevice d=r.getDevice();String a=safeAddress(d);DeviceRow row=devices.get(a);if(row==null){row=new DeviceRow(d);devices.put(a,row);addCard(row);}row.rssi=r.getRssi();row.record=r.getScanRecord();row.connectable=Build.VERSION.SDK_INT<26||r.isConnectable();row.txPower=r.getTxPower();updateCard(row);event("ADVERTISEMENT","name="+safeName(d)+";address="+a+";addressType="+addressType(d)+";bond="+bondState(d)+";connectable="+row.connectable+";rssi="+r.getRssi()+";tx="+r.getTxPower()+";services="+(r.getScanRecord()==null?"":r.getScanRecord().getServiceUuids())+";raw="+hex(r.getScanRecord()==null?null:r.getScanRecord().getBytes()));}@Override public void onScanFailed(int e){event("SCAN_ERROR","code="+e);runOnUiThread(()->{status.setText("● Tarama hatası: "+e);scan.setText("TARA");scanning=false;});}};
    @SuppressLint("MissingPermission")private void addCard(DeviceRow row){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(10),dp(7),dp(10),dp(7));c.setBackgroundResource(android.R.drawable.dialog_holo_light_frame);TextView top=label("",16),sub=label("",12),extra=label("",11);c.addView(top);c.addView(sub);c.addView(extra);c.setOnClickListener(v->selectDevice(row));c.setOnLongClickListener(v->{showDeviceDetails(row);return true;});row.card=top;deviceList.addView(c,new LinearLayout.LayoutParams(-1,dp(96)));updateCard(row);}
    @SuppressLint("MissingPermission")private void updateCard(DeviceRow r){if(r.card==null)return;ViewGroup c=(ViewGroup)r.card.getParent();r.card.setText((selected==r.device?"✓ ":"")+safeName(r.device));((TextView)c.getChildAt(1)).setText(safeAddress(r.device)+"   RSSI "+r.rssi+" dBm   "+(r.connectable?"CONNECTABLE":"NON-CONNECTABLE"));String x="TX "+r.txPower+" dBm   "+(r.record==null||r.record.getServiceUuids()==null?"0 services":r.record.getServiceUuids().size()+" services")+"   Bond "+bondState(r.device);((TextView)c.getChildAt(2)).setText(x+"   • Dokun: seç | Uzun bas: detay");count.setText(devices.size()+" cihaz");}
    @SuppressLint("MissingPermission")private void selectDevice(DeviceRow r){selected=r.device;selectedName=safeName(selected);selectedAddress=safeAddress(selected);connect.setEnabled(gatt==null&&!connecting);selectedInfo.setText("Seçili: "+selectedName+"  |  "+selectedAddress+"\nConnectable="+r.connectable+"  Bond="+bondState(selected)+"  AddressType="+addressType(selected));for(DeviceRow x:devices.values())updateCard(x);status.setText("● Cihaz seçildi — BAĞLAN'a bas");event("DEVICE_SELECTED",deviceIdentity(r));}
    @SuppressLint("MissingPermission")private String deviceIdentity(DeviceRow r){return "name="+safeName(r.device)+";address="+safeAddress(r.device)+";addressType="+addressType(r.device)+";bond="+bondState(r.device)+";rssi="+r.rssi+";connectable="+r.connectable+";tx="+r.txPower;}
    @SuppressLint("MissingPermission")private void showDeviceDetails(DeviceRow r){StringBuilder s=new StringBuilder();s.append("Name: ").append(safeName(r.device)).append("\nAddress: ").append(safeAddress(r.device)).append("\nAddress type: ").append(addressType(r.device)).append("\nBond state: ").append(bondState(r.device)).append("\nRSSI: ").append(r.rssi).append(" dBm\nConnectable: ").append(r.connectable).append("\nTX Power: ").append(r.txPower).append(" dBm\n");if(r.record!=null){s.append("Services: ").append(r.record.getServiceUuids()).append("\nService data: ").append(serviceData(r.record)).append("\nManufacturer data: ").append(manufacturerData(r.record)).append("\nRaw advertisement:\n").append(hex(r.record.getBytes()));}new AlertDialog.Builder(this).setTitle("Bluetooth Device Inspector").setMessage(s.toString()).setPositiveButton("SEÇ",(d,w)->selectDevice(r)).setNeutralButton("KAPAT",null).show();}

    @SuppressLint("MissingPermission")private void connectDevice(BluetoothDevice d){stopScan();cancelRetry();closeGatt();selected=d;selectedName=safeName(d);selectedAddress=safeAddress(d);retryCount=0;manualDisconnect=false;connecting=true;newCapture();event("CONNECT_START",deviceIdentity(findRow(d)));connect.setEnabled(false);disconnect.setEnabled(true);save.setEnabled(true);append("=== GATT CONNECT ===");append("Device: "+selectedName+" | "+selectedAddress);append("Address type: "+addressType(d)+" | Bond: "+bondState(d));startGattAttempt();}
    private DeviceRow findRow(BluetoothDevice d){for(DeviceRow r:devices.values())if(r.device.equals(d))return r;return new DeviceRow(d);}
    @SuppressLint("MissingPermission")private void startGattAttempt(){if(selected==null)return;int attempt=++retryCount;status.setText("● Bağlanıyor… deneme "+attempt+"/3");event("CONNECT_ATTEMPT","attempt="+attempt+";transport=AUTO;address="+selectedAddress+";bond="+bondState(selected));append("CONNECT ATTEMPT "+attempt+" / 3 — TRANSPORT_AUTO");gatt=selected.connectGatt(this,false,gattCallback,BluetoothDevice.TRANSPORT_AUTO);}
    private void retryConnection(int statusCode){if(manualDisconnect||selected==null){connecting=false;return;}if(retryCount>=3){connecting=false;runOnUiThread(()->{status.setText("● Bağlantı başarısız — status "+statusCode+" / "+gattStatus(statusCode));connect.setEnabled(selected!=null);disconnect.setEnabled(false);});event("CONNECT_FAILED","status="+statusCode+";name="+gattStatus(statusCode)+";address="+selectedAddress);return;}int delay=(int)(RETRY_BASE_MS*Math.pow(2,retryCount-1));event("CONNECT_RETRY","next_attempt="+(retryCount+1)+";delay_ms="+delay+";status="+statusCode);append("Retry in "+delay+" ms — previous="+statusCode+" / "+gattStatus(statusCode));closeGatt();handler.postDelayed(retryRunnable,delay);}
    private void cancelRetry(){handler.removeCallbacks(retryRunnable);}
    @SuppressLint("MissingPermission")private void closeGatt(){if(gatt!=null){try{gatt.disconnect();}catch(Exception ignored){}try{gatt.close();}catch(Exception ignored){}gatt=null;}}
    @SuppressLint("MissingPermission")private void disconnect(){manualDisconnect=true;connecting=false;event("DISCONNECT_REQUEST","manual");cancelRetry();if(gatt!=null)try{gatt.disconnect();}catch(Exception ignored){}runOnUiThread(()->{disconnect.setEnabled(false);connect.setEnabled(selected!=null);status.setText("● Bağlantı kesildi");});}

    private final BluetoothGattCallback gattCallback=new BluetoothGattCallback(){
      @Override public void onConnectionStateChange(BluetoothGatt g,int st,int state){event("GATT_STATE","state="+state+";status="+st+" ("+gattStatus(st)+")");if(state==BluetoothGatt.STATE_CONNECTED){connecting=false;runOnUiThread(()->{status.setText("● BAĞLI — MTU / servis keşfi");append("CONNECTED status="+st+" / "+gattStatus(st));});if(Build.VERSION.SDK_INT>=21)g.requestMtu(517);else g.discoverServices();}else if(state==BluetoothGatt.STATE_DISCONNECTED){if(!manualDisconnect)retryConnection(st);else runOnUiThread(()->{disconnect.setEnabled(false);connect.setEnabled(selected!=null);});}}
      @Override public void onMtuChanged(BluetoothGatt g,int mtu,int st){event("MTU","mtu="+mtu+";status="+st);append("MTU "+mtu+" / "+st);g.discoverServices();}
      @Override public void onServicesDiscovered(BluetoothGatt g,int st){if(st!=BluetoothGatt.GATT_SUCCESS){event("SERVICE_DISCOVERY_ERROR","status="+st+";"+gattStatus(st));append("SERVICE DISCOVERY ERROR "+st+" / "+gattStatus(st));return;}event("GATT_DISCOVERY","services="+g.getServices().size());readQueue.clear();readIndex=0;append("=== SERVICES "+g.getServices().size()+" ===");for(BluetoothGattService s:g.getServices()){event("SERVICE",s.getUuid()+";type="+s.getType());append("SERVICE "+s.getUuid());for(BluetoothGattCharacteristic c:s.getCharacteristics()){String p=properties(c.getProperties());event("CHARACTERISTIC",c.getUuid()+";properties="+p);append(" CHAR "+c.getUuid()+" ["+p+"]");for(BluetoothGattDescriptor d:c.getDescriptors()){event("DESCRIPTOR",d.getUuid().toString());append("  DESC "+d.getUuid());}if((c.getProperties()&BluetoothGattCharacteristic.PROPERTY_READ)!=0)readQueue.add(c);if((c.getProperties()&(BluetoothGattCharacteristic.PROPERTY_NOTIFY|BluetoothGattCharacteristic.PROPERTY_INDICATE))!=0)enableNotify(c);}}save.setEnabled(true);readNext();}
      @Override public void onCharacteristicRead(BluetoothGatt g,BluetoothGattCharacteristic c,byte[] v,int st){String h=hex(v);event("READ","uuid="+c.getUuid()+";status="+st+";hex="+h);append("READ "+c.getUuid()+" → "+h+" ["+st+"]");readIndex++;handler.postDelayed(MainActivity.this::readNext,120);}
      @Override public void onCharacteristicChanged(BluetoothGatt g,BluetoothGattCharacteristic c,byte[] v){String h=hex(v);event("NOTIFY","uuid="+c.getUuid()+";hex="+h);append("NOTIFY "+c.getUuid()+" → "+h);}
      @Override public void onDescriptorWrite(BluetoothGatt g,BluetoothGattDescriptor d,int st){event("DESCRIPTOR_WRITE","uuid="+d.getUuid()+";status="+st);}
    };
    @SuppressLint("MissingPermission")private void readNext(){if(gatt!=null&&readIndex<readQueue.size())gatt.readCharacteristic(readQueue.get(readIndex));else{event("CAPTURE_READY","reads="+readQueue.size()+";notifications="+notifySet.size());append("=== CAPTURE READY ===");status.setText("● Capture hazır — CAPTURE'a bas");}}
    @SuppressLint("MissingPermission")private void enableNotify(BluetoothGattCharacteristic c){String u=c.getUuid().toString();if(notifySet.contains(u)||gatt==null)return;notifySet.add(u);boolean ok=gatt.setCharacteristicNotification(c,true);event("NOTIFY_ENABLE",u+";local="+ok);BluetoothGattDescriptor d=c.getDescriptor(UUID.fromString("00002902-0000-1000-8000-00805f9b34fb"));if(d!=null){boolean ind=(c.getProperties()&BluetoothGattCharacteristic.PROPERTY_INDICATE)!=0;d.setValue(ind?BluetoothGattDescriptor.ENABLE_INDICATION_VALUE:BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE);gatt.writeDescriptor(d);}}
    private void newCapture(){capture.setLength(0);firstEvent=true;notifySet.clear();readQueue.clear();readIndex=0;capture.append("{\n  \"capture_version\":5,\n  \"started\":\"").append(ts()).append("\",\n  \"events\":[\n");}
    private void event(String type,String data){synchronized(capture){if(!firstEvent)capture.append(",\n");firstEvent=false;capture.append("    {\"time\":\"").append(esc(ts())).append("\",\"type\":\"").append(esc(type)).append("\",\"data\":\"").append(esc(data)).append("\"}");}}
    private void saveCapture(){String body=capture.toString()+"\n  ],\n  \"device\":{\"name\":\""+esc(selectedName)+"\",\"address\":\""+esc(selectedAddress)+"\"},\n  \"finished\":\""+ts()+"\"\n}\n";Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"buds2_capture_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date())+".json");pendingExport=body;startActivityForResult(i,CREATE_FILE);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==CREATE_FILE&&c==RESULT_OK&&d!=null){try(OutputStream o=getContentResolver().openOutputStream(d.getData())){o.write(pendingExport.getBytes("UTF-8"));append("CAPTURE SAVED → "+d.getData());status.setText("● Capture kaydedildi");}catch(Exception e){append("SAVE ERROR "+e);}}}
    private String properties(int p){StringBuilder s=new StringBuilder();if((p&BluetoothGattCharacteristic.PROPERTY_READ)!=0)s.append("READ ");if((p&BluetoothGattCharacteristic.PROPERTY_WRITE)!=0)s.append("WRITE ");if((p&BluetoothGattCharacteristic.PROPERTY_WRITE_NO_RESPONSE)!=0)s.append("WRITE_NR ");if((p&BluetoothGattCharacteristic.PROPERTY_NOTIFY)!=0)s.append("NOTIFY ");if((p&BluetoothGattCharacteristic.PROPERTY_INDICATE)!=0)s.append("INDICATE ");if((p&BluetoothGattCharacteristic.PROPERTY_BROADCAST)!=0)s.append("BROADCAST ");return s.toString().trim();}
    private String gattStatus(int s){switch(s){case 0:return"GATT_SUCCESS";case 8:return"GATT_CONN_TIMEOUT";case 19:return"GATT_CONN_TERMINATE_PEER_USER";case 22:return"GATT_CONN_TERMINATE_LOCAL_HOST";case 133:return"GATT_ERROR";case 147:return"GATT_CONNECTION_TIMEOUT_0x93";case 257:return"GATT_FAILURE/CONNECTION_CANCELLED";default:return"GATT_STATUS_"+s;}}
    private String addressType(BluetoothDevice d){if(Build.VERSION.SDK_INT>=31){try{return String.valueOf(d.getType());}catch(Exception e){return"unknown";}}return"legacy-api";}
    @SuppressLint("MissingPermission")private String bondState(BluetoothDevice d){try{switch(d.getBondState()){case BluetoothDevice.BOND_BONDED:return"BONDED";case BluetoothDevice.BOND_BONDING:return"BONDING";default:return"NONE";}}catch(Exception e){return"unknown";}}
    @SuppressLint("MissingPermission")private String serviceData(ScanRecord r){if(r==null||r.getServiceData()==null)return"{}";return r.getServiceData().toString();}
    @SuppressLint("MissingPermission")private String manufacturerData(ScanRecord r){if(r==null||r.getManufacturerSpecificData()==null)return"{}";return r.getManufacturerSpecificData().toString();}
    private String hex(byte[] v){if(v==null)return"null";StringBuilder s=new StringBuilder();for(byte b:v)s.append(String.format(Locale.US,"%02X ",b&255));return s.toString().trim();}
    @SuppressLint("MissingPermission")private String safeName(BluetoothDevice d){try{return d.getName()==null?"(isimsiz)":d.getName();}catch(Exception e){return"(izin yok)";}}
    @SuppressLint("MissingPermission")private String safeAddress(BluetoothDevice d){try{return d.getAddress();}catch(Exception e){return"unknown";}}
    private String esc(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n");}private String ts(){return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ",Locale.US).format(new Date());}
    private void append(String s){runOnUiThread(()->log.append(new SimpleDateFormat("HH:mm:ss.SSS",Locale.US).format(new Date())+"  "+s+"\n"));}private void msg(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_SHORT).show());append(s);}
    @Override protected void onDestroy(){if(scanner!=null)try{scanner.stopScan(scanCallback);}catch(Exception ignored){}manualDisconnect=true;handler.removeCallbacksAndMessages(null);closeGatt();super.onDestroy();}
}
