package com.yigit.buds2blescanner;

import android.Manifest;
import android.annotation.SuppressLint;
import android.app.Activity;
import android.bluetooth.*;
import android.bluetooth.le.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.os.*;
import android.view.ViewGroup;
import android.widget.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
 private static final int REQUEST_BT=1001,CREATE_FILE=2001; private static final long SCAN_TIME_MS=12000L;
 private BluetoothAdapter adapter; private BluetoothLeScanner scanner; private BluetoothGatt gatt; private final Handler handler=new Handler(Looper.getMainLooper());
 private TextView status,log; private Button scanButton,exportButton,connectButton,disconnectButton; private final StringBuilder capture=new StringBuilder();
 private final Set<String> notified=new HashSet<>(); private final List<BluetoothGattCharacteristic> readable=new ArrayList<>(); private int readIndex=0; private String deviceName="unknown",deviceAddress="unknown"; private BluetoothDevice selected; private String pendingExport="";
 @Override protected void onCreate(Bundle s){super.onCreate(s); BluetoothManager m=(BluetoothManager)getSystemService(Context.BLUETOOTH_SERVICE);adapter=m.getAdapter();buildUi();requestPermissionsIfNeeded();}
 private void buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);int p=dp(10);root.setPadding(p,p,p,p);TextView title=new TextView(this);title.setText("Galaxy Buds2 Analyzer");title.setTextSize(23);root.addView(title);status=new TextView(this);status.setText("● Hazır");status.setTextSize(16);root.addView(status);
  LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);scanButton=btn("TARA");connectButton=btn("BAĞLAN");disconnectButton=btn("KES");exportButton=btn("CAPTURE KAYDET");connectButton.setEnabled(false);disconnectButton.setEnabled(false);exportButton.setEnabled(false);scanButton.setOnClickListener(v->startScan());connectButton.setOnClickListener(v->{if(selected!=null)connect(selected);});disconnectButton.setOnClickListener(v->disconnect());exportButton.setOnClickListener(v->saveCapture());bar.addView(scanButton,w());bar.addView(connectButton,w());bar.addView(disconnectButton,w());bar.addView(exportButton,w());root.addView(bar);
  TextView h=new TextView(this);h.setText("CANLI ANALİZ / GATT / HEX");h.setTextSize(14);root.addView(h);ScrollView sc=new ScrollView(this);log=new TextView(this);log.setTextSize(12);log.setTextIsSelectable(true);sc.addView(log);root.addView(sc,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));setContentView(root);}
 private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}private LinearLayout.LayoutParams w(){return new LinearLayout.LayoutParams(0,-2,1);}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
 private void requestPermissionsIfNeeded(){if(Build.VERSION.SDK_INT>=31){if(checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)!=PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.BLUETOOTH_SCAN,Manifest.permission.BLUETOOTH_CONNECT},REQUEST_BT);}else if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION},REQUEST_BT);}
 @SuppressLint("MissingPermission") private boolean ready(){if(adapter==null){append("Bluetooth desteklenmiyor.");return false;}if(!adapter.isEnabled()){append("Bluetooth kapalı.");return false;}return Build.VERSION.SDK_INT<31||(checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)==PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)==PackageManager.PERMISSION_GRANTED);}
 private void newCapture(){capture.setLength(0);notified.clear();readable.clear();readIndex=0;capture.append("{\n  \"capture_version\": 2,\n  \"started\": \"").append(ts()).append("\",\n  \"events\": [\n");firstEvent=true;}
 private boolean firstEvent=true;private void event(String type,String data){synchronized(capture){if(!firstEvent)capture.append(",\n");firstEvent=false;capture.append("    {\"time\":\"").append(ts()).append("\",\"type\":\"").append(esc(type)).append("\",\"data\":\"").append(esc(data)).append("\"}");}}
 private String esc(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n");}private String ts(){return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ",Locale.US).format(new Date());}
 @SuppressLint("MissingPermission") private void startScan(){if(!ready())return;scanner=adapter.getBluetoothLeScanner();if(scanner==null){append("BLE scanner alınamadı.");return;}newCapture();append("=== BLE SCAN ===");event("SCAN_START","BLE scan started");status.setText("● Tarama yapılıyor...");scanButton.setEnabled(false);scanner.startScan(null,new ScanSettings.Builder().setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY).build(),callback);handler.postDelayed(this::stopScan,SCAN_TIME_MS);}
 @SuppressLint("MissingPermission") private void stopScan(){if(scanner!=null)scanner.stopScan(callback);scanButton.setEnabled(true);if(gatt==null)status.setText("● Tarama tamamlandı");event("SCAN_END","BLE scan ended");}
 private final ScanCallback callback=new ScanCallback(){@Override public void onScanResult(int type,ScanResult r){BluetoothDevice d=r.getDevice();String n=safeName(d),a=safeAddress(d);String adv=scanRecordHex(r.getScanRecord());append("DEVICE  "+n+" | "+a+" | RSSI="+r.getRssi());event("ADVERTISEMENT","name="+n+";address="+a+";rssi="+r.getRssi()+";txPower="+r.getTxPower()+";raw="+adv);if(n.toLowerCase(Locale.ROOT).contains("buds")){selected=d;connectButton.setEnabled(true);status.setText("● Buds cihazı bulundu — BAĞLAN'a bas");}}@Override public void onScanFailed(int e){append("SCAN ERROR "+e);event("SCAN_ERROR",String.valueOf(e));scanButton.setEnabled(true);}};
 @SuppressLint("MissingPermission") private String scanRecordHex(ScanRecord r){return r==null?"null":hex(r.getBytes());}
 @SuppressLint("MissingPermission") private void connect(BluetoothDevice d){stopScan();if(gatt!=null){try{gatt.close();}catch(Exception ignored){}gatt=null;}selected=d;deviceName=safeName(d);deviceAddress=safeAddress(d);newCapture();event("CONNECT_START",deviceName+"|"+deviceAddress);status.setText("● Bağlanıyor...");append("=== GATT CONNECT ===");connectButton.setEnabled(false);disconnectButton.setEnabled(true);exportButton.setEnabled(true);gatt=d.connectGatt(this,false,gattCallback,BluetoothDevice.TRANSPORT_LE);}
 @SuppressLint("MissingPermission") private void disconnect(){if(gatt!=null){try{gatt.disconnect();}catch(Exception ignored){}try{gatt.close();}catch(Exception ignored){}gatt=null;}disconnectButton.setEnabled(false);connectButton.setEnabled(selected!=null);status.setText("● Bağlantı kesildi");event("DISCONNECTED","manual");}
 private final BluetoothGattCallback gattCallback=new BluetoothGattCallback(){@Override public void onConnectionStateChange(BluetoothGatt g,int st,int state){if(state==BluetoothGatt.STATE_CONNECTED){event("CONNECTED","status="+st);runOnUiThread(()->{status.setText("● BAĞLI — otomatik capture aktif");append("CONNECTED → discoverServices()");});g.discoverServices();}else if(state==BluetoothGatt.STATE_DISCONNECTED){event("DISCONNECTED","status="+st);runOnUiThread(()->status.setText("● Bağlantı kesildi"));}}
  @Override public void onServicesDiscovered(BluetoothGatt g,int st){if(st!=BluetoothGatt.GATT_SUCCESS){event("SERVICE_DISCOVERY_ERROR",String.valueOf(st));append("Service discovery error "+st);return;}event("GATT_DISCOVERY","services="+g.getServices().size());readable.clear();append("=== ALL GATT ===");for(BluetoothGattService s:g.getServices()){append("SERVICE "+s.getUuid()+" type="+s.getType());event("SERVICE",s.getUuid()+" type="+s.getType());for(BluetoothGattCharacteristic c:s.getCharacteristics()){String p=properties(c.getProperties());append(" CHAR "+c.getUuid()+" ["+p+"]");event("CHARACTERISTIC",c.getUuid()+" properties="+p);for(BluetoothGattDescriptor d:c.getDescriptors()){append("  DESC "+d.getUuid());event("DESCRIPTOR",d.getUuid().toString());}if((c.getProperties()&BluetoothGattCharacteristic.PROPERTY_READ)!=0)readable.add(c);if((c.getProperties()&(BluetoothGattCharacteristic.PROPERTY_NOTIFY|BluetoothGattCharacteristic.PROPERTY_INDICATE))!=0)enableNotify(c);}}exportButton.setEnabled(true);readNext();}
  @Override public void onCharacteristicRead(BluetoothGatt g,BluetoothGattCharacteristic c,byte[] v,int st){String h=hex(v);append("READ "+c.getUuid()+" → "+h+" status="+st);event("READ","uuid="+c.getUuid()+";status="+st+";hex="+h);readIndex++;handler.postDelayed(MainActivity.this::readNext,100);}
  @Override public void onCharacteristicChanged(BluetoothGatt g,BluetoothGattCharacteristic c,byte[] v){String h=hex(v);append("NOTIFY "+c.getUuid()+" → "+h);event("NOTIFY","uuid="+c.getUuid()+";hex="+h);}
  @Override public void onDescriptorWrite(BluetoothGatt g,BluetoothGattDescriptor d,int st){event("DESCRIPTOR_WRITE","uuid="+d.getUuid()+";status="+st);}
 };
 @SuppressLint("MissingPermission") private void readNext(){if(gatt!=null&&readIndex<readable.size()){gatt.readCharacteristic(readable.get(readIndex));}else{event("CAPTURE_READY","automatic capture complete");status.setText("● Capture hazır — kaydet");append("=== CAPTURE TAMAMLANDI ===");exportButton.setEnabled(true);}}
 @SuppressLint("MissingPermission") private void enableNotify(BluetoothGattCharacteristic c){if(gatt==null||notified.contains(c.getUuid().toString()))return;notified.add(c.getUuid().toString());boolean ok=gatt.setCharacteristicNotification(c,true);event("NOTIFY_ENABLE",c.getUuid()+" local="+ok);BluetoothGattDescriptor d=c.getDescriptor(UUID.fromString("00002902-0000-1000-8000-00805f9b34fb"));if(d!=null){d.setValue((c.getProperties()&BluetoothGattCharacteristic.PROPERTY_INDICATE)!=0?BluetoothGattDescriptor.ENABLE_INDICATION_VALUE:BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE);gatt.writeDescriptor(d);}}
 private void saveCapture(){String body=capture.toString()+"\n  ],\n  \"device\":{\"name\":\""+esc(deviceName)+"\",\"address\":\""+esc(deviceAddress)+"\"},\n  \"finished\":\""+ts()+"\"\n}\n";Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"buds2_capture_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date())+".json");pendingExport=body;startActivityForResult(i,CREATE_FILE);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==CREATE_FILE&&c==RESULT_OK&&d!=null){try(OutputStream o=getContentResolver().openOutputStream(d.getData())){o.write(pendingExport.getBytes("UTF-8"));append("CAPTURE KAYDEDİLDİ: "+d.getData());status.setText("● Capture kaydedildi");}catch(Exception e){append("SAVE ERROR "+e);}}}
 private String properties(int p){StringBuilder s=new StringBuilder();if((p&BluetoothGattCharacteristic.PROPERTY_READ)!=0)s.append("READ ");if((p&BluetoothGattCharacteristic.PROPERTY_WRITE)!=0)s.append("WRITE ");if((p&BluetoothGattCharacteristic.PROPERTY_WRITE_NO_RESPONSE)!=0)s.append("WRITE_NR ");if((p&BluetoothGattCharacteristic.PROPERTY_NOTIFY)!=0)s.append("NOTIFY ");if((p&BluetoothGattCharacteristic.PROPERTY_INDICATE)!=0)s.append("INDICATE ");if((p&BluetoothGattCharacteristic.PROPERTY_BROADCAST)!=0)s.append("BROADCAST ");return s.toString().trim();}
 private String hex(byte[] v){if(v==null)return"null";StringBuilder s=new StringBuilder();for(byte b:v)s.append(String.format(Locale.US,"%02X ",b&255));return s.toString().trim();}
 @SuppressLint("MissingPermission") private String safeName(BluetoothDevice d){try{return d.getName()==null?"unknown":d.getName();}catch(Exception e){return"unknown";}}@SuppressLint("MissingPermission") private String safeAddress(BluetoothDevice d){try{return d.getAddress();}catch(Exception e){return"unknown";}}
 private void append(String t){runOnUiThread(()->log.append(new SimpleDateFormat("HH:mm:ss.SSS",Locale.US).format(new Date())+"  "+t+"\n"));}
 @Override protected void onDestroy(){if(scanner!=null)try{scanner.stopScan(callback);}catch(Exception ignored){}if(gatt!=null){try{gatt.disconnect();}catch(Exception ignored){}gatt.close();}super.onDestroy();}
}
