package com.yigit.buds2blescanner;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Typeface;
import android.os.Bundle;
import android.widget.*;
import com.yigit.buds2blescanner.protocol.Ayf1FirmwareProfile;

/**
 * Android parity shell inspired by the open-source GalaxyBudsClient page model.
 * This project is independently implemented; protocol behavior is enabled only
 * where the inspected GalaxyBudsClient sources provide a verified message path.
 */
public class ProfessionalDashboardActivity extends Activity {
    private LinearLayout content; private TextView pageTitle,connection;
    @Override public void onCreate(Bundle state){super.onCreate(state);build();showDashboard();}
    private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
    private TextView label(String s,float size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setPadding(dp(12),dp(8),dp(12),dp(8));return t;}
    private Button nav(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
    private TextView card(String title,String value){TextView t=label(title+"\n"+value,15);t.setPadding(dp(16),dp(14),dp(16),dp(14));return t;}
    private void build(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(8),dp(8),dp(8),dp(8));
        LinearLayout header=new LinearLayout(this);header.setOrientation(LinearLayout.VERTICAL);pageTitle=label("GALAXY BUDS2 CLIENT PRO",24);pageTitle.setTypeface(Typeface.DEFAULT,Typeface.BOLD);connection=label("● SM-R177 / AYF1 protocol engine hazır",13);header.addView(pageTitle);header.addView(connection);root.addView(header);
        HorizontalScrollView ns=new HorizontalScrollView(this);LinearLayout navBar=new LinearLayout(this);navBar.setOrientation(LinearLayout.HORIZONTAL);
        String[] names={"Home","Buds2","Sound Studio","Noise Control","Equalizer","Ambient","Touch","Conversation","Spatial","Find My","Fit Test","Diagnostics","Capture","Protocol","AYF1 Firmware","Devices","System Info","Advanced","Settings","Hotkeys","Bixby","FMM","Hidden","Usage","Rename","About"};
        Button[] buttons=new Button[names.length];for(int i=0;i<names.length;i++){buttons[i]=nav(names[i]);navBar.addView(buttons[i]);}ns.addView(navBar);root.addView(ns);
        ScrollView scroll=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        buttons[0].setOnClickListener(v->showDashboard());buttons[1].setOnClickListener(v->showBuds());buttons[2].setOnClickListener(v->showStudio());buttons[3].setOnClickListener(v->showNoise());buttons[4].setOnClickListener(v->showEqualizer());buttons[5].setOnClickListener(v->showAmbient());buttons[6].setOnClickListener(v->showTouch());buttons[7].setOnClickListener(v->showConversation());buttons[8].setOnClickListener(v->showSpatial());buttons[9].setOnClickListener(v->showFindMy());buttons[10].setOnClickListener(v->showFitTest());buttons[11].setOnClickListener(v->showDiagnostics());buttons[12].setOnClickListener(v->showCapture());buttons[13].setOnClickListener(v->showProtocol());buttons[14].setOnClickListener(v->showFirmware());buttons[15].setOnClickListener(v->showDevices());buttons[16].setOnClickListener(v->showSystemInfo());buttons[17].setOnClickListener(v->showAdvanced());buttons[18].setOnClickListener(v->showSettings());buttons[19].setOnClickListener(v->showHotkeys());buttons[20].setOnClickListener(v->showBixby());buttons[21].setOnClickListener(v->showFmm());buttons[22].setOnClickListener(v->showHidden());buttons[23].setOnClickListener(v->showUsage());buttons[24].setOnClickListener(v->showRename());buttons[25].setOnClickListener(v->showAbout());setContentView(root);
    }
    private void clear(String title){pageTitle.setText(title);content.removeAllViews();}
    private void locked(String what){content.addView(card("CAPABILITY GATE",what+"\nKaynakta/firmware sembolü bulundu; R177 wire TX'si doğrulanmadıkça gönderim kilitli."));}
    private void openControls(){startActivity(new Intent(this,Ayf1ControlsActivity.class));}
    private void showDashboard(){clear("HOME");content.addView(card("DEVICE","Galaxy Buds2 / SM-R177\nFirmware: "+Ayf1FirmwareProfile.VERSION));content.addView(card("TRANSPORT","Buds2 SPP New\nUUID 2e73a4ad-332d-41fc-90e2-16bef06523f2"));content.addView(card("CLIENT PARITY","Home · Devices · Noise Control · Equalizer · Ambient Customize · Touch · Fit Test · Find My · Spatial · System · Advanced · Settings"));content.addView(card("PROTOCOL","FD / 16-bit size / message ID / payload / CRC16-CCITT / DD"));content.addView(card("SAFETY","Unknown/debug/FOTA TX disabled until device-specific behavior is verified."));Button open=nav("OPEN LIVE CONTROLS");open.setOnClickListener(v->openControls());content.addView(open);Button diag=nav("OPEN VERIFIED DIAGNOSTICS");diag.setOnClickListener(v->startActivity(new Intent(this,Ayf1DiagnosticsActivity.class)));content.addView(diag);}
    private void showBuds(){clear("BUDS2 DEVICE");content.addView(card("IDENTITY","SM-R177 · Galaxy Buds2\nR177XXU0AYF1"));content.addView(card("TRANSPORT","Bluetooth Classic → RFCOMM/SPP New\nUUID 2e73a4ad-332d-41fc-90e2-16bef06523f2"));content.addView(card("STATE","Battery · Wearing · Ambient · EQ · Touch · Connection · Version · Status · Extended Status"));openLive();}
    private void showStudio(){clear("SOUND STUDIO");content.addView(card("CLIENT EQ","GalaxyBudsClient exposes the Buds2 hardware EQ presets through message 134."));content.addView(card("PRO AUDIO EXTRA","24-band parametric workspace, FFT/RMS, reference curves and custom analysis are app-side extras and do not replace the Buds2's firmware EQ."));content.addView(card("PRESETS","Bass · Soft · Dynamic · Clear · Treble"));openLive();}
    private void showNoise(){clear("NOISE CONTROL");content.addView(card("VERIFIED","NOISE_CONTROLS=120 · OFF / ANC / AMBIENT"));content.addView(card("ANC","NOISE_REDUCTION_LEVEL=131 · SET_ANC_WITH_ONE_EARBUD=111"));content.addView(card("CONVERSATION","SET_DETECT_CONVERSATIONS=122 · DURATION=123"));openLive();}
    private void showEqualizer(){clear("EQUALIZER");content.addView(card("MESSAGE","EQUALIZER=134"));content.addView(card("BUDS2 PAYLOAD","Disabled = 0; enabled preset = Preset+1, as implemented by GalaxyBudsClient's SetEqualizerEncoder."));content.addView(card("PRESETS","Off · Bass · Soft · Dynamic · Clear · Treble"));openLive();}
    private void showAmbient(){clear("AMBIENT CUSTOMIZE");content.addView(card("MESSAGES","SET_AMBIENT_MODE=128 · CUSTOMIZE_AMBIENT_SOUND=130 · AMBIENT_VOLUME=132"));content.addView(card("CONTROLS","Mode · Volume · Custom ambient parameters where supported by device spec."));openLive();}
    private void showTouch(){clear("TOUCH");content.addView(card("MESSAGES","LOCK_TOUCHPAD=144 · SET_TOUCHPAD_OPTION=146 · SET_TOUCHPAD_OTHER_OPTION=147 · TOUCH_UPDATED=145"));content.addView(card("GESTURES","Single · Double · Triple · Hold · Touch-and-hold noise control cycle"));openLive();}
    private void showConversation(){clear("CONVERSATION DETECTION");content.addView(card("MESSAGES","122 enable/disable · 123 duration"));content.addView(card("TIMEOUT","5 s · 10 s · 15 s"));openLive();}
    private void showSpatial(){clear("SPATIAL AUDIO");content.addView(card("MESSAGES","SET_SPATIAL_AUDIO=124 · SPATIAL_AUDIO_DATA=194 · SPATIAL_AUDIO_CONTROL=195"));content.addView(card("SENSOR","GRV / gyro calibration payload decoding is supported in the diagnostics engine."));openLive();}
    private void showFindMy(){clear("FIND MY BUDS");content.addView(card("MESSAGES","160 start · 161 stop · 162 mute status/control family"));content.addView(card("BEHAVIOR","Stops automatically when leaving the page, matching the upstream page behavior."));openLive();}
    private void showFitTest(){clear("FIT TEST");content.addView(card("VERIFIED","CHECK_THE_FIT_OF_EARBUDS=157 · RESULT=158"));content.addView(card("RESULT","0 Bad · 1 Good · 2 TestFailed; left/right result bytes."));Button x=nav("RUN FIT TEST");x.setOnClickListener(v->startActivity(new Intent(this,Ayf1DiagnosticsActivity.class)));content.addView(x);}
    private void showDiagnostics(){clear("DIAGNOSTICS");content.addView(card("SELF TEST","171 · 32-bit result bitmap with hardware/software/touch/accelerometer/proximity/thermistor/ADC/Hall checks."));content.addView(card("FIT TEST","157 request / 158 result."));content.addView(card("SPATIAL","194 event data; GRV and gyro calibration decoding."));content.addView(card("ACT / FOTA / DEBUG","Message catalogued, but active transmission remains gated for R177 until a device-specific TX path is verified."));Button x=nav("OPEN DIAGNOSTICS");x.setOnClickListener(v->startActivity(new Intent(this,Ayf1DiagnosticsActivity.class)));content.addView(x);}
    private void showCapture(){clear("CAPTURE LAB");content.addView(card("RAW","RX/TX stream with timestamps, direction and hexadecimal payload."));content.addView(card("FRAME","FD · 16-bit little-endian size · ID · payload · CRC16-CCITT · DD"));content.addView(card("DISCOVERY","Message IDs · payload lengths · CRC · response correlation · protocol variants."));openLive();}
    private void showProtocol(){clear("PROTOCOL LAB");content.addView(card("KNOWN MESSAGE IDS","0–255 catalog is available in the Live Controls Protocol Catalog."));content.addView(card("VERIFIED FAMILY","Status 96 · Extended Status 97 · Connection 98 · Version 99 · Noise 120–123 · Spatial 124/194/195 · EQ 134 · Fit 157/158 · Find 160/161 · Self Test 171."));content.addView(card("UNKNOWN TX","Never transmitted automatically."));openLive();}
    private void showFirmware(){clear("AYF1 FIRMWARE");content.addView(card("TARGET",Ayf1FirmwareProfile.summary()));content.addView(card("FLASH","BASE 0x28000000 · SIZE 0x800000 · OTA CODE 0x18000 · OTA REMAP 0x320000"));content.addView(card("CRC32","0x"+Long.toHexString(Ayf1FirmwareProfile.IMAGE_CRC32).toUpperCase()));StringBuilder f=new StringBuilder();for(String n:Ayf1FirmwareProfile.features().keySet())f.append("• ").append(n).append('\n');content.addView(card("FEATURE CATALOG",f.toString().trim()));}
    private void showDevices(){clear("DEVICES");content.addView(card("DEVICE SELECTION","Eşleşmiş Bluetooth cihazlarını seç ve Buds2 SPP New ile bağlan."));content.addView(card("MODEL","SM-R177 / Buds2"));openLive();}
    private void showSystemInfo(){clear("SYSTEM INFO");content.addView(card("MESSAGES","STATUS_UPDATED=96 · EXTENDED_STATUS_UPDATED=97 · CONNECTION_UPDATED=98 · VERSION_INFO=99"));content.addView(card("TELEMETRY","Battery · wearing · connection · firmware/version · thermal/status fields when supplied by device."));}
    private void showAdvanced(){clear("ADVANCED");content.addView(card("UPSTREAM CATEGORIES","Debug mode · ACT test · log/trace · coredump · properties · hidden commands · FOTA."));locked("Advanced/debug/FOTA commands are intentionally not blindly enabled on R177.");}
    private void showSettings(){clear("SETTINGS");content.addView(card("CONNECTION","Buds2 SPP New UUID · automatic bonded-device discovery."));content.addView(card("CAPTURE","Timestamped TX/RX logging."));content.addView(card("SAFETY","Unknown command gate · verified-only diagnostics."));content.addView(card("APP","Android 11–16 target path; source-derived parity UI."));}
    private void showHotkeys(){clear("HOTKEYS");content.addView(card("UPSTREAM FEATURE","GalaxyBudsClient supports configurable hot commands/events."));locked("Android global hotkeys require a separate permission/service implementation.");}
    private void showBixby(){clear("BIXBY / VOICE");content.addView(card("MESSAGES","SET_BIXBY_KEYWORD=102 · SET_VOICE_WAKE_UP=151 · VOICE_WAKE_UP_LANGUAGE=153 · VOICE_WAKE_UP_EVENT=154"));locked("Device-specific voice-wake payloads.");}
    private void showFmm(){clear("FMM / FIND MY MOBILE");content.addView(card("MESSAGES","SET_FMM_CONFIG=172 · GET_FMM_CONFIG=173"));locked("FMM account/service integration is not inferred from firmware symbols alone.");}
    private void showHidden(){clear("HIDDEN / DEBUG");content.addView(card("UPSTREAM","Hidden mode/data, factory info, debug SKU/version, water history, coredump and trace facilities exist in the protocol catalog."));locked("Hidden/factory/debug commands.");}
    private void showUsage(){clear("USAGE REPORT");content.addView(card("MESSAGES","USAGE_REPORT=64 · USAGE_REPORT_V2=71 · METERING_REPORT=65"));content.addView(card("CAPTURE","Raw report decoding can be added from the upstream decoders without enabling destructive TX.") );}
    private void showRename(){clear("RENAME");content.addView(card("DEVICE NAME","GalaxyBudsClient has a Rename page. Android implementation will write only a verified property/message path."));locked("Rename TX until the exact R177 property encoder is verified.");}
    private void showAbout(){clear("ABOUT");content.addView(card("PROJECT","Galaxy Buds2 Client Pro — Android implementation for SM-R177 / AYF1."));content.addView(card("SOURCE BASIS","Protocol research uses the open-source GalaxyBudsClient project, which is GPL-3.0 licensed."));content.addView(card("IMPORTANT","This app is not Samsung's official app and does not flash firmware by default."));}
    private void openLive(){Button x=nav("OPEN LIVE CONTROLS");x.setOnClickListener(v->openControls());content.addView(x);}
}
